name: ej1-workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm i
      - run: npm test

      - name: Construir imagen
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: webapp
